[theme]
# Primary accent color for interactive elements.
primaryColor = "#7f90b8"  # Adjusted for comfort

# Background color for the main content area.
backgroundColor = "#f2f2f2"  # Adjusted for comfort

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#c3d2e4"  # Adjusted for comfort

# Color used for almost all text.
textColor = "#333333"  # Adjusted for comfort
